### PR TITLE
    SWITCHYARD-2595 Knowledge TypeResource not getting loaded in karaf

### PR DESCRIPTION
**Pull request by dvirgiln**
https://issues.jboss.org/browse/SWITCHYARD-2595

### CODE REVIEW

**Comment by kcbabo** [comment]
Seems strange to include component paths in a core class.  Why is the second properties file not found on Karaf?  Is it a path/visibility issue and is that the root cause we should fix?  If that can't be done, perhaps consider an overloaded version of this method which supports passing in additional URL paths to load vs. storing extra paths outside of core?

**Comment by dvirgiln** [comment]
Hi Keith, 

I did not want to modify many classes for this little issue. The problem is that in karaf it can not be loaded files in the same package && name . I will only find one item (the first). 

Then if this solution is not suitable, I have to modify the CommonKnowledge component model to create a KnowledgeManifest that would contains a List of KnowledgeResource objects.

The KnowledgeManifest extends Manifest and the KnowledgeResource extends Resource..

If you consider so, I ll go for this solution.

**Comment by kcbabo** [comment]
Perhaps we should take a step back before discussing a code change.  This works on EAP, right?  If so, why is the extra path required on Karaf and not on EAP?

**Comment by dvirgiln** [comment]
I need to check in debug mode what is returning Classes.getResources in eap. As the quickstart works in EAP I imagine, it will return all the items that can be found with the path put as param. In our case it will return two URLs, the one that is in switchyard-common project and the one that is inside of knowledge-common-component.

In karaf ( checked with Freeman) it returns just the first item found with that path.

This solution that I wrote will not affect the eap deployments.

**Comment by kcbabo** [comment]
This solution introduces component-specific code into core, which we try to avoid if possible.  I need a little bit more detail to understand your explanation.  You have stated:
"The problem is that in karaf it can not be loaded files in the same package && name"
and 
"In karaf ( checked with Freeman) it returns just the first item found with that path."

What is "it" above?  Which files have the same package and name?

**Comment by dvirgiln** [comment]
It is specified here: 
https://issues.jboss.org/browse/SWITCHYARD-2595

These are the two files that in eap are returned as a list of 2 items, and in eap just one:

https://github.com/dvirgiln/core/blob/master/common/core/src/main/resources/org/switchyard/common/io/resource/resourceType.properties

https://github.com/dvirgiln/components/blob/master/common/knowledge/src/main/resources/org/switchyard/common/io/resource/resourceType.properties

**Comment by kcbabo** [comment]
Yeah, but your diff references this (nonexistent) file:
/org/switchyard/component/common/knowledge/resource/resourceType.properties
https://github.com/dvirgiln/core/commit/08e9d9713c2ff4813de890b7f11ffb807b08ab70#diff-cb8766032058b5117c2d1db30a7ed40dR181

**Pull request closed without merging**
